# Generated by Django 2.2.6 on 2019-11-05 19:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('courses_app', '0002_auto_20191105_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['course', 'student', 'status']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='app',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
